name: Android dev APK build

on:
  push:
    branches: [ development ]
  workflow_dispatch: {}

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK (platform 35)
        uses: r0adkll/setup-android@v2
        with:
          api-level: 35
          build-tools: '35.0.0'
          ndk: '27.1.12297006'
          components: 'platform-tools,platforms;android-35,build-tools;35.0.0,ndk;27.1.12297006'

      - name: Install Bun (CI)
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "BUN_INSTALL_DIR=$HOME/.bun/bin" >> $GITHUB_ENV
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install node dependencies (bun)
        run: |
          cd delivra
          bun install --frozen-lockfile || bun install

      - name: Ensure expo-dev-client present
        run: |
          cd delivra
          # ensure dev-client is available in CI; harmless if already present
          bun add expo-dev-client || true

      - name: Build Android debug APK
        run: |
          cd delivra/android
          chmod +x ./gradlew
          ./gradlew clean assembleDebug --no-daemon

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: delivra/android/app/build/outputs/apk/debug/*.apk
