name: Android Release Build

on:
  push:
    branches: [ main, test-build ]
  pull_request:
    branches: [ main, test-build ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: React Native Android Build APK
        uses: realabbas/Github-Actions-React-Native@v1.1.2

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: delivra/android/app/build/outputs/apk/release/*.apk
