name: YAML Lint

on:
  push:
    branches: [ main, test-build ]
  pull_request:
    branches: [ main, test-build ]
  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install yamllint

      - name: Run yamllint on .github
        run: |
          yamllint -f colored -s .github || true
